// <auto-generated />
using System;
using System.Collections.Generic;
using Concordat.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Concordat.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ConcordatDbContext))]
    [Migration("20260814052033_EnvironmentsAndBrokers")]
    partial class EnvironmentsAndBrokers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Concordat.Domain.Registry.Environment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<string>("RegistrationPolicy")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("registration_policy");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "DefaultCompatibilityPolicy", "Concordat.Domain.Registry.Environment.DefaultCompatibilityPolicy#CompatibilityPolicy", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Mode")
                                .IsRequired()
                                .HasMaxLength(24)
                                .HasColumnType("character varying(24)")
                                .HasColumnName("default_compatibility_mode");

                            b1.Property<string>("Surface")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("default_compatibility_surface");
                        });

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_environment_tenant_name");

                    b.ToTable("environment", (string)null);
                });

            modelBuilder.Entity("Concordat.Domain.Registry.Schema", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character(32)")
                        .HasColumnName("schema_id")
                        .IsFixedLength();

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(524288)
                        .HasColumnType("character varying(524288)")
                        .HasColumnName("body");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("format");

                    b.HasKey("Id");

                    b.ToTable("schema", null, t =>
                        {
                            t.HasCheckConstraint("ck_schema_id_is_lower_hex", "schema_id ~ '^[0-9a-f]{32}$'");
                        });
                });

            modelBuilder.Entity("Concordat.Domain.Registry.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<string>("ContentModel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("content_model");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("format");

                    b.Property<string>("Lifecycle")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("lifecycle");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("owner");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "CompatibilityPolicy", "Concordat.Domain.Registry.Subject.CompatibilityPolicy#CompatibilityPolicy", b1 =>
                        {
                            b1.Property<string>("Mode")
                                .IsRequired()
                                .HasMaxLength(24)
                                .HasColumnType("character varying(24)")
                                .HasColumnName("compatibility_mode");

                            b1.Property<string>("Surface")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("compatibility_surface");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Latest", "Concordat.Domain.Registry.Subject.Latest#LatestPointer", b1 =>
                        {
                            b1.Property<DateTimeOffset>("MovedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("latest_moved_at");

                            b1.Property<string>("MovedBy")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("latest_moved_by");

                            b1.Property<int>("Ordinal")
                                .HasColumnType("integer")
                                .HasColumnName("latest_ordinal");
                        });

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "EnvironmentId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_subject_name_per_environment");

                    b.ToTable("subject", (string)null);
                });

            modelBuilder.Entity("Concordat.Domain.Registry.Environment", b =>
                {
                    b.OwnsMany("Concordat.Domain.Registry.BrokerConnection", "Brokers", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("broker_id");

                            b1.Property<string>("CredentialRef")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("credential_ref");

                            b1.Property<string>("DisplayName")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("display_name");

                            b1.Property<DateTimeOffset?>("LastCheckedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("last_checked_at");

                            b1.Property<string>("LastError")
                                .HasMaxLength(1024)
                                .HasColumnType("character varying(1024)")
                                .HasColumnName("last_error");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("status");

                            b1.Property<string>("Uri")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("uri");

                            b1.Property<bool>("UseTls")
                                .HasColumnType("boolean")
                                .HasColumnName("use_tls");

                            b1.Property<string>("VirtualHost")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("virtual_host");

                            b1.Property<Guid>("environment_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("environment_id");

                            b1.ToTable("broker_connection", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("environment_id");
                        });

                    b.Navigation("Brokers");
                });

            modelBuilder.Entity("Concordat.Domain.Registry.Schema", b =>
                {
                    b.OwnsMany("Concordat.Domain.Registry.Reference", "References", b1 =>
                        {
                            b1.Property<string>("schema_id")
                                .HasColumnType("character(32)");

                            b1.Property<string>("Name")
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("name");

                            b1.Property<string>("Subject")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("subject");

                            b1.Property<int>("Version")
                                .HasColumnType("integer")
                                .HasColumnName("version");

                            b1.HasKey("schema_id", "Name");

                            b1.HasIndex("Subject", "Version")
                                .HasDatabaseName("ix_schema_reference_target");

                            b1.ToTable("schema_reference", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("schema_id");
                        });

                    b.Navigation("References");
                });

            modelBuilder.Entity("Concordat.Domain.Registry.Subject", b =>
                {
                    b.OwnsMany("Concordat.Domain.Registry.SchemaVersion", "Versions", b1 =>
                        {
                            b1.Property<Guid>("subject_id")
                                .HasColumnType("uuid");

                            b1.Property<int>("Ordinal")
                                .HasColumnType("integer")
                                .HasColumnName("ordinal");

                            b1.Property<string>("Changelog")
                                .HasMaxLength(4000)
                                .HasColumnType("character varying(4000)")
                                .HasColumnName("changelog");

                            b1.Property<DateTimeOffset?>("DecidedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("decided_at");

                            b1.Property<string>("DecidedBy")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("decided_by");

                            b1.Property<bool>("Deprecated")
                                .HasColumnType("boolean")
                                .HasColumnName("deprecated");

                            b1.Property<DateTimeOffset>("RegisteredAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("registered_at");

                            b1.Property<string>("RegisteredBy")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("registered_by");

                            b1.Property<string>("SchemaId")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character(32)")
                                .HasColumnName("schema_id")
                                .IsFixedLength();

                            b1.Property<string>("SemanticVersion")
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("semver");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(24)
                                .HasColumnType("character varying(24)")
                                .HasColumnName("status");

                            b1.HasKey("subject_id", "Ordinal");

                            b1.HasIndex("SchemaId")
                                .HasDatabaseName("ix_schema_version_schema_id");

                            b1.ToTable("schema_version", null, t =>
                                {
                                    t.HasCheckConstraint("ck_schema_version_ordinal_positive", "ordinal >= 1");
                                });

                            b1.WithOwner()
                                .HasForeignKey("subject_id");
                        });

                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
