// <auto-generated />
using System;
using System.Collections.Generic;
using Concordat.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Concordat.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ConcordatDbContext))]
    [Migration("20260814115000_Tenancy")]
    partial class Tenancy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Concordat.Domain.Contracts.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Enforcement")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("enforcement");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "EnvironmentId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_contract_tenant_environment_name");

                    b.ToTable("contract", (string)null);
                });

            modelBuilder.Entity("Concordat.Domain.Governance.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("actor");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("Detail")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("detail");

                    b.Property<Guid?>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("target");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "At")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_audit_tenant_at");

                    b.HasIndex("TenantId", "EnvironmentId", "At")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_audit_tenant_environment_at");

                    b.HasIndex("TenantId", "Target", "At")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_audit_tenant_target_at");

                    b.ToTable("audit_entry", (string)null);
                });

            modelBuilder.Entity("Concordat.Domain.Governance.NotificationSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("subscription_id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("endpoint");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<string>("Events")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("events");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "EnvironmentId")
                        .HasDatabaseName("ix_subscription_tenant_environment");

                    b.ToTable("notification_subscription", (string)null);
                });

            modelBuilder.Entity("Concordat.Domain.Governance.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(8192)
                        .HasColumnType("character varying(8192)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event");

                    b.Property<string>("LastError")
                        .HasMaxLength(8192)
                        .HasColumnType("character varying(8192)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<bool>("Parked")
                        .HasColumnType("boolean")
                        .HasColumnName("parked");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("target");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "NextAttemptAt")
                        .HasDatabaseName("ix_outbox_due")
                        .HasFilter("delivered_at IS NULL AND parked = false");

                    b.ToTable("outbox_message", (string)null);
                });

            modelBuilder.Entity("Concordat.Domain.Governance.ServiceRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<string>("Consumes")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("consumes");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("Produces")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("produces");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "EnvironmentId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_service_tenant_environment_name");

                    b.ToTable("service_registration", (string)null);
                });

            modelBuilder.Entity("Concordat.Domain.Identity.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("api_key_id");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("actor");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("key_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("label");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("scopes");

                    b.Property<string>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("secret_hash");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("KeyId")
                        .IsUnique()
                        .HasDatabaseName("ux_api_key_key_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_api_key_tenant");

                    b.ToTable("api_key", (string)null);
                });

            modelBuilder.Entity("Concordat.Domain.Identity.Membership", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("membership_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_membership_tenant_user");

                    b.ToTable("membership", (string)null);
                });

            modelBuilder.Entity("Concordat.Domain.Identity.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_tenant_slug");

                    b.ToTable("tenant", (string)null);
                });

            modelBuilder.Entity("Concordat.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean")
                        .HasColumnName("disabled");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("LastSignedInAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_signed_in_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_user_email");

                    b.ToTable("app_user", (string)null);
                });

            modelBuilder.Entity("Concordat.Domain.Registry.Environment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<string>("RegistrationPolicy")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("registration_policy");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "DefaultCompatibilityPolicy", "Concordat.Domain.Registry.Environment.DefaultCompatibilityPolicy#CompatibilityPolicy", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Mode")
                                .IsRequired()
                                .HasMaxLength(24)
                                .HasColumnType("character varying(24)")
                                .HasColumnName("default_compatibility_mode");

                            b1.Property<string>("Surface")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("default_compatibility_surface");
                        });

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_environment_tenant_name");

                    b.ToTable("environment", (string)null);
                });

            modelBuilder.Entity("Concordat.Domain.Registry.Schema", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character(32)")
                        .HasColumnName("schema_id")
                        .IsFixedLength();

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(524288)
                        .HasColumnType("character varying(524288)")
                        .HasColumnName("body");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("format");

                    b.HasKey("Id");

                    b.ToTable("schema", null, t =>
                        {
                            t.HasCheckConstraint("ck_schema_id_is_lower_hex", "schema_id ~ '^[0-9a-f]{32}$'");
                        });
                });

            modelBuilder.Entity("Concordat.Domain.Registry.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<string>("ContentModel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("content_model");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("format");

                    b.Property<string>("Lifecycle")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("lifecycle");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("owner");

                    b.Property<int>("Revision")
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "CompatibilityPolicy", "Concordat.Domain.Registry.Subject.CompatibilityPolicy#CompatibilityPolicy", b1 =>
                        {
                            b1.Property<string>("Mode")
                                .IsRequired()
                                .HasMaxLength(24)
                                .HasColumnType("character varying(24)")
                                .HasColumnName("compatibility_mode");

                            b1.Property<string>("Surface")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("compatibility_surface");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Latest", "Concordat.Domain.Registry.Subject.Latest#LatestPointer", b1 =>
                        {
                            b1.Property<DateTimeOffset>("MovedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("latest_moved_at");

                            b1.Property<string>("MovedBy")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("latest_moved_by");

                            b1.Property<int>("Ordinal")
                                .HasColumnType("integer")
                                .HasColumnName("latest_ordinal");
                        });

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "EnvironmentId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_subject_name_per_environment");

                    b.ToTable("subject", (string)null);
                });

            modelBuilder.Entity("Concordat.Infrastructure.Persistence.StoredCredential", b =>
                {
                    b.Property<string>("Reference")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("credential_ref");

                    b.Property<string>("Ciphertext")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("ciphertext");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Reference");

                    b.ToTable("broker_credential", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Concordat.Domain.Contracts.Contract", b =>
                {
                    b.OwnsMany("Concordat.Domain.Contracts.ConsumeBinding", "Consumes", b1 =>
                        {
                            b1.Property<Guid>("contract_id")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Queue")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("queue");

                            b1.Property<string>("Subjects")
                                .IsRequired()
                                .HasMaxLength(4096)
                                .HasColumnType("character varying(4096)")
                                .HasColumnName("subjects");

                            b1.HasKey("contract_id", "Id");

                            b1.ToTable("consume_binding", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("contract_id");

                            b1.OwnsOne("Concordat.Domain.Contracts.TopologyScope", "Scope", b2 =>
                                {
                                    b2.Property<Guid>("ConsumeBindingcontract_id")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("ConsumeBindingId")
                                        .HasColumnType("integer");

                                    b2.Property<Guid?>("BrokerId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("broker_id");

                                    b2.Property<string>("VirtualHost")
                                        .IsRequired()
                                        .HasMaxLength(256)
                                        .HasColumnType("character varying(256)")
                                        .HasColumnName("virtual_host");

                                    b2.HasKey("ConsumeBindingcontract_id", "ConsumeBindingId");

                                    b2.ToTable("consume_binding");

                                    b2.WithOwner()
                                        .HasForeignKey("ConsumeBindingcontract_id", "ConsumeBindingId");
                                });

                            b1.Navigation("Scope")
                                .IsRequired();
                        });

                    b.OwnsMany("Concordat.Domain.Contracts.PublishBinding", "Publishes", b1 =>
                        {
                            b1.Property<Guid>("contract_id")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Exchange")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("exchange");

                            b1.Property<int?>("Precedence")
                                .HasColumnType("integer")
                                .HasColumnName("precedence");

                            b1.Property<string>("RoutingKeyPattern")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("routing_key_pattern");

                            b1.Property<string>("Subjects")
                                .IsRequired()
                                .HasMaxLength(4096)
                                .HasColumnType("character varying(4096)")
                                .HasColumnName("subjects");

                            b1.HasKey("contract_id", "Id");

                            b1.ToTable("publish_binding", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("contract_id");

                            b1.OwnsOne("Concordat.Domain.Contracts.TopologyScope", "Scope", b2 =>
                                {
                                    b2.Property<Guid>("PublishBindingcontract_id")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("PublishBindingId")
                                        .HasColumnType("integer");

                                    b2.Property<Guid?>("BrokerId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("broker_id");

                                    b2.Property<string>("VirtualHost")
                                        .IsRequired()
                                        .HasMaxLength(256)
                                        .HasColumnType("character varying(256)")
                                        .HasColumnName("virtual_host");

                                    b2.HasKey("PublishBindingcontract_id", "PublishBindingId");

                                    b2.ToTable("publish_binding");

                                    b2.WithOwner()
                                        .HasForeignKey("PublishBindingcontract_id", "PublishBindingId");
                                });

                            b1.Navigation("Scope")
                                .IsRequired();
                        });

                    b.Navigation("Consumes");

                    b.Navigation("Publishes");
                });

            modelBuilder.Entity("Concordat.Domain.Registry.Environment", b =>
                {
                    b.OwnsMany("Concordat.Domain.Registry.BrokerConnection", "Brokers", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("broker_id");

                            b1.Property<string>("CredentialRef")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("credential_ref");

                            b1.Property<string>("DisplayName")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("display_name");

                            b1.Property<DateTimeOffset?>("LastCheckedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("last_checked_at");

                            b1.Property<string>("LastError")
                                .HasMaxLength(1024)
                                .HasColumnType("character varying(1024)")
                                .HasColumnName("last_error");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("status");

                            b1.Property<string>("Uri")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("uri");

                            b1.Property<bool>("UseTls")
                                .HasColumnType("boolean")
                                .HasColumnName("use_tls");

                            b1.Property<string>("VirtualHost")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("virtual_host");

                            b1.Property<Guid>("environment_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("environment_id");

                            b1.ToTable("broker_connection", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("environment_id");
                        });

                    b.Navigation("Brokers");
                });

            modelBuilder.Entity("Concordat.Domain.Registry.Schema", b =>
                {
                    b.OwnsMany("Concordat.Domain.Registry.Reference", "References", b1 =>
                        {
                            b1.Property<string>("schema_id")
                                .HasColumnType("character(32)");

                            b1.Property<string>("Name")
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("name");

                            b1.Property<string>("Subject")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("subject");

                            b1.Property<int>("Version")
                                .HasColumnType("integer")
                                .HasColumnName("version");

                            b1.HasKey("schema_id", "Name");

                            b1.HasIndex("Subject", "Version")
                                .HasDatabaseName("ix_schema_reference_target");

                            b1.ToTable("schema_reference", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("schema_id");
                        });

                    b.Navigation("References");
                });

            modelBuilder.Entity("Concordat.Domain.Registry.Subject", b =>
                {
                    b.OwnsMany("Concordat.Domain.Registry.SchemaVersion", "Versions", b1 =>
                        {
                            b1.Property<Guid>("subject_id")
                                .HasColumnType("uuid");

                            b1.Property<int>("Ordinal")
                                .HasColumnType("integer")
                                .HasColumnName("ordinal");

                            b1.Property<string>("Changelog")
                                .HasMaxLength(4000)
                                .HasColumnType("character varying(4000)")
                                .HasColumnName("changelog");

                            b1.Property<DateTimeOffset?>("DecidedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("decided_at");

                            b1.Property<string>("DecidedBy")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("decided_by");

                            b1.Property<bool>("Deprecated")
                                .HasColumnType("boolean")
                                .HasColumnName("deprecated");

                            b1.Property<DateTimeOffset>("RegisteredAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("registered_at");

                            b1.Property<string>("RegisteredBy")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("registered_by");

                            b1.Property<string>("SchemaId")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character(32)")
                                .HasColumnName("schema_id")
                                .IsFixedLength();

                            b1.Property<string>("SemanticVersion")
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("semver");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(24)
                                .HasColumnType("character varying(24)")
                                .HasColumnName("status");

                            b1.HasKey("subject_id", "Ordinal");

                            b1.HasIndex("SchemaId")
                                .HasDatabaseName("ix_schema_version_schema_id");

                            b1.ToTable("schema_version", null, t =>
                                {
                                    t.HasCheckConstraint("ck_schema_version_ordinal_positive", "ordinal >= 1");
                                });

                            b1.WithOwner()
                                .HasForeignKey("subject_id");
                        });

                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
